// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkP9gIK-0ZTq9bGKuNDTe6mGX6xbSYFNs',
    appId: '1:488111375762:web:c5598af237c49de4c7ad4b',
    messagingSenderId: '488111375762',
    projectId: 'musicmate-d438a',
    authDomain: 'musicmate-d438a.firebaseapp.com',
    databaseURL: 'https://musicmate-d438a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicmate-d438a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3Ma4cvxfz-88uvu_1RMF6G615ds-FWA',
    appId: '1:488111375762:android:3238643290ec3749c7ad4b',
    messagingSenderId: '488111375762',
    projectId: 'musicmate-d438a',
    databaseURL: 'https://musicmate-d438a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicmate-d438a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzdNUi60YGQvDBNi-wX0FJu5aDjasygY',
    appId: '1:488111375762:ios:aad9da386b76360fc7ad4b',
    messagingSenderId: '488111375762',
    projectId: 'musicmate-d438a',
    databaseURL: 'https://musicmate-d438a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicmate-d438a.appspot.com',
    androidClientId: '488111375762-k6pg3el9ivo5qn41s4hdo9q8sr78t61g.apps.googleusercontent.com',
    iosClientId: '488111375762-6lqcuh58kg69q0f8711t9f5bvo71k32v.apps.googleusercontent.com',
    iosBundleId: 'com.musicmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzdNUi60YGQvDBNi-wX0FJu5aDjasygY',
    appId: '1:488111375762:ios:aad9da386b76360fc7ad4b',
    messagingSenderId: '488111375762',
    projectId: 'musicmate-d438a',
    databaseURL: 'https://musicmate-d438a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicmate-d438a.appspot.com',
    androidClientId: '488111375762-k6pg3el9ivo5qn41s4hdo9q8sr78t61g.apps.googleusercontent.com',
    iosClientId: '488111375762-6lqcuh58kg69q0f8711t9f5bvo71k32v.apps.googleusercontent.com',
    iosBundleId: 'com.musicmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkP9gIK-0ZTq9bGKuNDTe6mGX6xbSYFNs',
    appId: '1:488111375762:web:b8a3819933f6d8bfc7ad4b',
    messagingSenderId: '488111375762',
    projectId: 'musicmate-d438a',
    authDomain: 'musicmate-d438a.firebaseapp.com',
    databaseURL: 'https://musicmate-d438a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicmate-d438a.appspot.com',
  );

}